export type Subcategory =
  | 'ARCHITECTURE_AND_ENGINEERING_OCCUPATIONS'
  | 'ARTS,_DESIGN,_ENTERTAINMENT,_SPORTS,_AND_MEDIA_OCCUPATIONS'
  | 'BUILDING_AND_GROUNDS_CLEANING_AND_MAINTENANCE_OCCUPATIONS'
  | 'BUSINESS_AND_FINANCIAL_OPERATIONS_OCCUPATIONS'
  | 'COMMUNITY_AND_SOCIAL_SERVICE_OCCUPATIONS'
  | 'COMPUTER_AND_MATHEMATICAL_OCCUPATIONS'
  | 'CONSTRUCTION_AND_EXTRACTION_OCCUPATIONS'
  | 'EDUCATIONAL_INSTRUCTION_AND_LIBRARY_OCCUPATIONS'
  | 'FARMING,_FISHING,_AND_FORESTRY_OCCUPATIONS'
  | 'FOOD_PREPARATION_AND_SERVING_RELATED_OCCUPATIONS'
  | 'HEALTHCARE_PRACTITIONERS_AND_TECHNICAL_OCCUPATIONS'
  | 'HEALTHCARE_SUPPORT_OCCUPATIONS'
  | 'INSTALLATION,_MAINTENANCE,_AND_REPAIR_OCCUPATIONS'
  | 'LEGAL_OCCUPATIONS'
  | 'LIFE,_PHYSICAL,_AND_SOCIAL_SCIENCE_OCCUPATIONS'
  | 'MANAGEMENT_OCCUPATIONS'
  | 'OFFICE_AND_ADMINISTRATIVE_SUPPORT_OCCUPATIONS'
  | 'PERSONAL_CARE_AND_SERVICE_OCCUPATIONS'
  | 'PRODUCTION_OCCUPATIONS'
  | 'PROTECTIVE_SERVICE_OCCUPATIONS'
  | 'SALES_AND_RELATED_OCCUPATIONS'
  | 'TRANSPORTATION_AND_MATERIAL_MOVING_OCCUPATIONS';

export type MainCategory =
  | 'MANAGEMENT, PROFESSIONAL, AND RELATED OCCUPATIONS'
  | 'MANAGEMENT, BUSINESS, AND FINANCIAL OPERATIONS OCCUPATIONS'
  | 'PROFESSIONAL AND RELATED OCCUPATIONS'
  | 'SERVICE OCCUPATIONS'
  | 'SALES AND OFFICE OCCUPATIONS'
  | 'OFFICE AND ADMINISTRATIVE SUPPORT OCCUPATIONS'
  | 'NATURAL RESOURCES, CONSTRUCTION, AND MAINTENANCE OCCUPATIONS'
  | 'FARMING, FISHING, AND FORESTRY OCCUPATIONS'
  | 'CONSTRUCTION AND EXTRACTION OCCUPATIONS'
  | 'INSTALLATION, MAINTENANCE, AND REPAIR OCCUPATIONS'
  | 'PRODUCTION OCCUPATIONS'
  | 'TRANSPORTATION AND MATERIAL MOVING OCCUPATIONS';

export const mapSubcategoryToMainCategory = (subcategory: Subcategory): MainCategory | null => {
  switch (subcategory) {
    case 'ARCHITECTURE_AND_ENGINEERING_OCCUPATIONS':
    case 'ARTS,_DESIGN,_ENTERTAINMENT,_SPORTS,_AND_MEDIA_OCCUPATIONS':
    case 'BUILDING_AND_GROUNDS_CLEANING_AND_MAINTENANCE_OCCUPATIONS':
    case 'BUSINESS_AND_FINANCIAL_OPERATIONS_OCCUPATIONS':
    case 'COMMUNITY_AND_SOCIAL_SERVICE_OCCUPATIONS':
    case 'COMPUTER_AND_MATHEMATICAL_OCCUPATIONS':
    case 'EDUCATIONAL_INSTRUCTION_AND_LIBRARY_OCCUPATIONS':
    case 'FARMING,_FISHING,_AND_FORESTRY_OCCUPATIONS':
    case 'FOOD_PREPARATION_AND_SERVING_RELATED_OCCUPATIONS':
    case 'HEALTHCARE_PRACTITIONERS_AND_TECHNICAL_OCCUPATIONS':
    case 'HEALTHCARE_SUPPORT_OCCUPATIONS':
    case 'LEGAL_OCCUPATIONS':
      return 'PROFESSIONAL AND RELATED OCCUPATIONS';

    case 'MANAGEMENT_OCCUPATIONS':
      return 'MANAGEMENT, PROFESSIONAL, AND RELATED OCCUPATIONS';

    case 'OFFICE_AND_ADMINISTRATIVE_SUPPORT_OCCUPATIONS':
      return 'OFFICE AND ADMINISTRATIVE SUPPORT OCCUPATIONS';

    case 'PERSONAL_CARE_AND_SERVICE_OCCUPATIONS':
    case 'PRODUCTION_OCCUPATIONS':
    case 'PROTECTIVE_SERVICE_OCCUPATIONS':
      return 'SERVICE OCCUPATIONS';

    case 'SALES_AND_RELATED_OCCUPATIONS':
      return 'SALES AND OFFICE OCCUPATIONS';

    case 'CONSTRUCTION_AND_EXTRACTION_OCCUPATIONS':
      return 'NATURAL RESOURCES, CONSTRUCTION, AND MAINTENANCE OCCUPATIONS';

    case 'INSTALLATION,_MAINTENANCE,_AND_REPAIR_OCCUPATIONS':
      return 'NATURAL RESOURCES, CONSTRUCTION, AND MAINTENANCE OCCUPATIONS';

    case 'TRANSPORTATION_AND_MATERIAL_MOVING_OCCUPATIONS':
      return 'TRANSPORTATION AND MATERIAL MOVING OCCUPATIONS';

    default:
      return null; // Return null if subcategory is not found
  }
};
